const Discord = require('discord.js');

exports.run = async (client, message, args) => {
 
   let hEmbed = new Discord.RichEmbed()
   .setTitle("Ninja Gen Help")
   .setColor("0x0ffff")
   .setDescription(`<@${message.author.id}>` + " My general command usage can be found below")
   .addField("About The Bot", "``gen about`` - Shows you some info about me and my team")
   .addBlankField()
   .addField("Generator Commands", "``gen commands`` - Shows a list of Account Generator commands")
   .addBlankField()
   .addField("Generator Categories", "``gen catergories`` - Shows all account categories and stock")
   .addBlankField()
   .addField("Invite The Bot", "``gen invite`` - Generates a invite link")
   .addBlankField()
   .addField("Report A Bug", "``gen bugreport {Reason}`` - Sends a message to the support server so the devs know about the bug you reported")
   .addBlankField()
   .addField("Account/Stock Request", "``gen request {YourRequest}`` - Sends a message to the support server so the devs know what you requested")
   .addBlankField()
   .addField("Developer Reminder", "``gen reminder`` - Sends a reminder to the support server **DEVELOPERS & BOT OWNER ONLY**")
   .addBlankField()
   .addField("List Of Servers", "``gen serverlist`` - Shows a list of servers i am in")
   .addBlankField()
   .addField("Current Server Info", "``gen serverinfo`` - Shows information for the current server")
   .addBlankField()
   .addField("Timed LockDown", "``gen timedlokcdown {duration}`` Locks the current channel for the set amount of time. **TIME MUST BE IN HOURS, MINUTES OR SECONDS** Example: ``gen timedlockdown 1h``")
   .addBlankField()
   .addField("Fight A User", "``gen fight @Tyler. H#9393`` Uses randomly generated answers to help you win or lose a fight with the mentioned member")
   .addBlankField()
   .addField("Ping The Bot", "``gen ping`` Pings the bot and checks for Response time, Latency and API issues")
   .addBlankField()
   .addField("Java Code Eval", "``gen eval {JavaScript Code Here}`` Evaluates the given code and returns the response")
   .addBlankField()
   .addField("Message Vote", "``gen vote {Message Here}`` Posts the message and allows members **15 Minutes** to vote yes or no")
   .addBlankField()
   .addField("Set Game", "``gen setgame {Game Here}`` Sets the game the bot is Playing Example: ``gen setgame Playing GTA 5``")
   .addBlankField()
   .addField("Set Status", "``gen setstatus {Status}`` Sets the bots online status Example: ``gen setstatus Idle`` Statuses: ``Idle, Online, DND, Away``")
   .addBlankField()
   .addField("Bot Uptime", "``gen uptime`` Shows how long the bot has been online since it's last restart")
   .setFooter(`© Ninja Gen Beta`, `https://i.imgur.com/xerUkNI.png`)
   .setThumbnail(`https://i.imgur.com/xerUkNI.png`)
   message.channel.send(hEmbed)
   message.delete().catch();	
 };
